name: run main.py

on:
  push: # Trigger workflow on every new commit
    branches:
      - main # Replace with your branch name if different
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # Checkout the repository content to the self-hosted runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Install the Python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # Run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: |
          set -e # Exit on error
          python main.py || echo "Python script encountered an error but continuing."
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
